### ISSUE TITLE
Chapter 2 동작 파라미터화 코드 전달하기

### ISSUE THREAD

**Issue by Tianea2160** [Tianea2160/ModernJavaInActionStudy#2]

**Comment by Tianea2160** [comment]
https://magical-fluorine-7a0.notion.site/chatper-2-Behavior-parameterization-3c73d7983e374f56a5b3161dfe07d5a3

**Comment by jojiapp** [comment]
https://chill-dove-7c6.notion.site/Chapter2-19cddefa43f34a2c874ee769b4a93926

**Comment by Raemerrr** [comment]
https://fish-hoodie-b32.notion.site/2-716b12d3cd984c0aadcb1170ac233501

**Comment by jurlring** [comment]
https://velog.io/@jurlring/%EB%8F%99%EC%9E%91-%ED%8C%8C%EB%9D%BC%EB%AF%B8%ED%84%B0-%ED%99%94

**Comment by hyunaseodev** [comment]
https://hyunaseo.notion.site/Part1-ch2-2e3eb32ec2f148f7904bd1d784ae7387

**Comment by doxxx93** [comment]
https://velog.io/@doxxx93/Chapter-2.-%EB%8F%99%EC%9E%91-%ED%8C%8C%EB%9D%BC%EB%AF%B8%ED%84%B0%ED%99%94-%EC%BD%94%EB%93%9C-%EC%A0%84%EB%8B%AC%ED%95%98%EA%B8%B0
