### ISSUE TITLE
Chapter 3 람다 표현식

### ISSUE THREAD

**Issue by Tianea2160** [Tianea2160/ModernJavaInActionStudy#3]

**Comment by Tianea2160** [comment]
https://magical-fluorine-7a0.notion.site/chapter-3-22f78997b95c4fe394561760eba3c1ef

**Comment by jurlring** [comment]
https://velog.io/@jurlring/%EB%9E%8C%EB%8B%A4Ramda-%EC%95%8C%EA%B3%A0-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0-%EA%B8%B0%EB%B3%B8%ED%8E%B8

https://velog.io/@jurlring/%EB%9E%8C%EB%8B%A4-%ED%91%9C%ED%98%84%EC%8B%9DLambda-%EC%95%8C%EA%B3%A0-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0-%EC%9D%91%EC%9A%A9%ED%8E%B8

**Comment by dding94** [comment]
https://valley-road-6eb.notion.site/0f6fdef55ce44006b8d6f16ac373165b

**Comment by Raemerrr** [comment]
https://fish-hoodie-b32.notion.site/3-fd7c296d0fb347fe88dbb2b436d47353

**Comment by hyunaseodev** [comment]
https://hyunaseo.notion.site/Part1-ch3-8094ce3f8f5649d5808cec7b620ba21b

**Comment by doxxx93** [comment]
https://velog.io/@doxxx93/%EB%AA%A8%EB%8D%98-%EC%9E%90%EB%B0%94-%EC%9D%B8-%EC%95%A1%EC%85%98

**Comment by jojiapp** [comment]
https://github.com/jojiapp/TIL/blob/master/java/Modern-Java-in-Action/part-1-%EA%B8%B0%EC%B4%88/Chapter-3-%EB%9E%8C%EB%8B%A4-%ED%91%9C%ED%98%84%EC%8B%9D.md
